sonar.projectKey=LuisHBarros_LuisHBarros-Python-devops
sonar.organization=luishbarros

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=LuisHBarros-Python-devops
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.sources=backend,frontend/src
sonar.tests=backend/users/tests

sonar.exclusions=**/migrations/**,**/__pycache__/**,**/node_modules/**,frontend/dist/**,**/*.test.ts,**/*.test.tsx,**/tests/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.typescript.tsconfigPaths=frontend/tsconfig.app.json
