sonar.projectKey=conteiners
sonar.projectName=Conteiners

sonar.sources=backend,frontend/src
sonar.tests=backend/users/tests

sonar.exclusions=**/migrations/**,**/__pycache__/**,**/node_modules/**,frontend/dist/**,**/*.test.ts,**/*.test.tsx

sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.typescript.tsconfigPaths=frontend/tsconfig.app.json
